from __future__ import annotations

from .core import DialogueIndexDB, DialogueVersionDB
from .core.models import (
    CommandBundle,
    CommandToken,
    DeletedBlockAction,
    DialogueSegment,
    FileSession,
    InsertedBlockAction,
    MergeBlocksAction,
    NO_SPEAKER_KEY,
    ResetBlockAction,
    SplitOverflowAction,
    StructuralAction,
)
from .core.parser import parse_dialogue_data, parse_dialogue_file
from .core.text_utils import (
    chunk_lines,
    collapse_lines_join_paragraphs,
    collapse_lines_force,
    first_overflow_char_index,
    fuzzy_compare_text,
    looks_like_name_line,
    natural_sort_key,
    normalize_control_code_word_case,
    preview_text,
    similarity_signature,
    smart_collapse_lines,
    smart_collapse_lines_space_efficient,
    split_lines_preserve_empty,
    unique_preserve_order,
    visible_length,
    wrap_lines_hard_break,
    wrap_lines_keep_breaks,
    wrap_text_word_aware,
)

__all__ = [
    "CommandBundle",
    "CommandToken",
    "DeletedBlockAction",
    "DialogueIndexDB",
    "DialogueVersionDB",
    "DialogueSegment",
    "FileSession",
    "InsertedBlockAction",
    "MergeBlocksAction",
    "NO_SPEAKER_KEY",
    "ResetBlockAction",
    "SplitOverflowAction",
    "StructuralAction",
    "chunk_lines",
    "collapse_lines_join_paragraphs",
    "collapse_lines_force",
    "first_overflow_char_index",
    "fuzzy_compare_text",
    "looks_like_name_line",
    "natural_sort_key",
    "normalize_control_code_word_case",
    "parse_dialogue_data",
    "parse_dialogue_file",
    "preview_text",
    "similarity_signature",
    "smart_collapse_lines",
    "smart_collapse_lines_space_efficient",
    "split_lines_preserve_empty",
    "unique_preserve_order",
    "visible_length",
    "wrap_lines_hard_break",
    "wrap_lines_keep_breaks",
    "wrap_text_word_aware",
]
